# Generated by Django 2.1 on 2019-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('marks', models.FloatField()),
                ('addr', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
